/* Tile Tumble: a store tile-matching solitaire (2000). Stacked layouts of picture tiles; remove matching
   pairs of free tiles (nothing on top, and a free left or right side) until the board is clear.
   Every deal is generated by removing pairs from the full layout, so it can always be solved. */
(function () {
  'use strict';
  const TW = 36, TH = 46, DZ = 7;   // tile face size and layer lift, in logical px

  /* ---------- layouts: [dx, dy (half-tiles), rows]; '#' is a tile ---------- */
  const LAYOUTS = [
    { id: 'pyramid', name: 'Pyramid', stars: 1, pay: 3, layers: [
      [0, 0, ['.########.', '.########.', '.########.', '##########', '##########', '.########.', '.########.', '.########.']],
      [4, 2, ['######', '######', '######', '######', '######', '######']],
      [6, 4, ['####', '####', '####', '####']],
      [8, 6, ['##', '##']]] },
    { id: 'bridge', name: 'Bridge', stars: 2, pay: 4, layers: [
      [0, 0, ['.##......##.', '.##......##.', '############', '############', '############', '.#..#..#..#.', '.#..#..#..#.', '.#..#..#..#.']],
      [0, 0, ['.##......##.', '.##......##.', '############', '.##########.', '............', '.#..#..#..#.', '.#..#..#..#.']],
      [0, 0, ['.##......##.', '.##......##.', '...######...', '...######...']],
      [0, 0, ['.##......##.', '.##......##.']],
      [0, 0, ['.##......##.', '.##......##.']]] },
    { id: 'butterfly', name: 'Butterfly', stars: 2, pay: 4, layers: [
      [0, 0, ['###.#..#.###', '####....####', '#####..#####', '.##########.', '.##########.', '#####..#####', '####....####', '###......###']],
      [0, 0, ['.##......##.', '.###....###.', '.####..####.', '.....##.....', '.....##.....', '.####..####.', '.###....###.', '.##......##.']],
      [0, 0, ['............', '..##....##..', '..###..###..', '.....##.....', '.....##.....', '..###..###..', '..##....##..']],
      [0, 0, ['............', '............', '..#......#..', '.....##.....', '.....##.....', '..#......#..']]] },
    { id: 'spiral', name: 'Spiral', stars: 3, pay: 5, layers: [
      [0, 0, ['############', '...........#', '.#########.#', '.#.......#.#', '.#.#####.#.#', '.#.#...#.#.#', '.#.###.#.#.#', '.#.....#...#']],
      [0, 0, ['############', '...........#', '.#########.#', '.#.......#.#', '.#.#####.#.#', '.#.#...#.#.#', '.#.###.#.#.#', '.#.....#...#']],
      [0, 0, ['............', '............', '.#########..', '.#.......#..', '.#.#####.#..', '.#.#...#.#..', '.#.###.#.#..', '.#.....#....']],
      [0, 0, ['............', '............', '............', '............', '...#####....', '...#...#....', '...##..#....']]] },
    { id: 'rocket', name: 'Rocket', stars: 3, pay: 5, layers: [
      [0, 0, ['##..........', '.##.#####...', '..#########.', '############', '############', '..#########.', '.##.#####...', '##..........']],
      [0, 0, ['............', '....#####...', '...#######..', '..#########.', '..#########.', '...#######..', '....#####...']],
      [0, 0, ['............', '.....####...', '....######..', '...########.', '...########.', '....######..', '.....####...']],
      [0, 0, ['............', '............', '............', '.....###....', '.....###....']]] },
    { id: 'fortress', name: 'Fortress', stars: 4, pay: 6, layers: [
      [0, 0, ['##.######.##', '############', '.##########.', '.##########.', '.##########.', '.##########.', '############', '##.######.##']],
      [0, 0, ['##........##', '##.######.##', '..#......#..', '..#.####.#..', '..#.####.#..', '..#......#..', '##.######.##', '##........##']],
      [0, 0, ['##........##', '##........##', '............', '............', '............', '............', '##........##', '##........##']]] }
  ];
  function positions(L) {
    const t = [];
    L.layers.forEach(([dx, dy, rows], z) => rows.forEach((r, ry) => [...r].forEach((c, cx) => { if (c === '#') t.push({ x: cx * 2 + dx, y: ry * 2 + dy, z }); })));
    return t;
  }

  /* ---------- tile art: 36 kinds in six suits, drawn in a 32x32 box ---------- */
  const SUITS = ['#c0282e', '#23408e', '#12877f', '#8a5a1c', '#2b8fd6', '#7b3fb5'];
  const ART = [
    // fruits
    '<path d="M16 10c-3-2-10-2-11 5-1 6 4 13 8 13 1 0 2-1 3-1s2 1 3 1c4 0 9-7 8-13-1-7-8-7-11-5z" fill="#d8262c" stroke="#7a1015"/><path d="M16 10c0-3 1-5 3-7" stroke="#6b3b12" stroke-width="1.8" fill="none"/><path d="M18 7c2-3 6-4 8-3-2 4-5 4-8 3z" fill="#3a9a2a"/><ellipse cx="10.5" cy="15" rx="1.6" ry="3" fill="#fff" opacity=".55"/>',
    '<path d="M10 20C12 12 15 7 20 4M22 21C21 13 21 8 20 4" stroke="#4d7a1c" stroke-width="1.6" fill="none"/><path d="M20 4c3-2 7-1 8 1-3 2-6 1-8-1z" fill="#3a9a2a"/><circle cx="9.5" cy="23" r="5.5" fill="#c3102a" stroke="#6d0615"/><circle cx="22" cy="24" r="5.5" fill="#c3102a" stroke="#6d0615"/><circle cx="7.8" cy="21.3" r="1.4" fill="#fff" opacity=".6"/><circle cx="20.3" cy="22.3" r="1.4" fill="#fff" opacity=".6"/>',
    '<path d="M5 9c1 10 11 18 23 12l0-3c-9 4-17-1-20-10z" fill="#f4d23a" stroke="#a88410" stroke-linejoin="round"/><path d="M8 11c3 6 9 10 17 9" stroke="#fff3a0" stroke-width="1.4" fill="none"/><rect x="4" y="6.5" width="3" height="3.5" fill="#6b4a12"/><rect x="27" y="17" width="2.5" height="3" fill="#3b2a0a"/>',
    '<path d="M16 3v5" stroke="#6b3b12" stroke-width="2"/><path d="M17 6c3-3 8-3 10 0-4 2-7 2-10 0z" fill="#3a9a2a"/><g fill="#7b2f9e" stroke="#40104f"><circle cx="10" cy="11" r="3.6"/><circle cx="16" cy="11" r="3.6"/><circle cx="22" cy="11" r="3.6"/><circle cx="13" cy="17" r="3.6"/><circle cx="19" cy="17" r="3.6"/><circle cx="16" cy="23" r="3.6"/><circle cx="10.5" cy="17.5" r="0"/></g><g fill="#fff" opacity=".45"><circle cx="9" cy="10" r="1"/><circle cx="15" cy="10" r="1"/><circle cx="12" cy="16" r="1"/><circle cx="15" cy="22" r="1"/></g>',
    '<path d="M16 6c-3 0-4 3-4 6 0 3-6 5-6 11 0 4 4 7 10 7s10-3 10-7c0-6-6-8-6-11 0-3-1-6-4-6z" fill="#9cc93a" stroke="#4f6e14"/><path d="M16 6c0-2 1-4 2-5" stroke="#6b3b12" stroke-width="1.6" fill="none"/><path d="M18 4c2-2 5-2 6-1-2 2-4 2-6 1z" fill="#3a9a2a"/><ellipse cx="11" cy="21" rx="1.5" ry="3" fill="#fff" opacity=".45"/>',
    '<circle cx="16" cy="18" r="11" fill="#f28a16" stroke="#9a4d06"/><path d="M16 7c1-3 4-4 7-3-1 3-4 4-7 3z" fill="#3a9a2a"/><circle cx="16" cy="7.5" r="1.2" fill="#5a3a0a"/><g fill="#d06d08"><circle cx="11" cy="16" r=".8"/><circle cx="20" cy="14" r=".8"/><circle cx="21" cy="22" r=".8"/><circle cx="13" cy="23" r=".8"/><circle cx="17" cy="19" r=".8"/></g><ellipse cx="11" cy="13" rx="2.5" ry="1.5" fill="#fff" opacity=".45"/>',
    // space
    '<circle cx="16" cy="16" r="12" fill="#2a6fd6" stroke="#0f2f6a"/><path d="M9 9c3-2 6 0 6 3s-4 3-5 6-3 2-4 0-1-7 3-9zM18 15c2-2 6-1 7 2s0 6-3 6-2-2-4-3 0-3 0-5zM14 25c2 0 4 1 3 2-2 1-4 0-3-2z" fill="#4caf3a"/><path d="M8 7c3-2 7-3 10-2" stroke="#fff" stroke-width="1.2" opacity=".5" fill="none"/>',
    '<ellipse cx="16" cy="17" rx="14" ry="4.5" fill="none" stroke="#c9a15a" stroke-width="2.2" transform="rotate(-18 16 17)"/><circle cx="16" cy="16" r="7.5" fill="#e3c27a" stroke="#8a6a2a"/><path d="M9.5 14h13M9 17h14" stroke="#c49a4a" stroke-width="1.3"/><path d="M4.5 21.5C8 24 20 20 27.5 12.5" stroke="#c9a15a" stroke-width="2.2" fill="none" transform="rotate(0)"/>',
    '<circle cx="16" cy="16" r="11" fill="#d2552a" stroke="#7a2a10"/><g fill="#a83c1a"><circle cx="12" cy="12" r="2.5"/><circle cx="20" cy="19" r="3"/><circle cx="13" cy="21" r="1.6"/><circle cx="21" cy="11" r="1.2"/></g><path d="M9 9c2-2 5-3 8-3" stroke="#f0a070" stroke-width="1.2" fill="none"/>',
    '<circle cx="16" cy="16" r="12" fill="#e8d2a8" stroke="#8a6a3a"/><path d="M6 11h20M4.5 16h23M6 21h20" stroke="#b86a38" stroke-width="2.4"/><path d="M8 26h16" stroke="#c9905a" stroke-width="1.6"/><ellipse cx="20" cy="19" rx="3.2" ry="2" fill="#b8321c"/>',
    '<path d="M21 4a12 12 0 1 0 0 24a9.5 9.5 0 1 1 0-24z" fill="#f5e9a8" stroke="#9a8a3a"/><g fill="#d8c878"><circle cx="11" cy="12" r="1.6"/><circle cx="9" cy="19" r="1.2"/><circle cx="13" cy="24" r="1.4"/></g><g fill="#f5d33a"><path d="M25 12l1 2 2 1-2 1-1 2-1-2-2-1 2-1z"/></g>',
    '<path d="M4 28L20 12l3 3z" fill="#9fd8ff" opacity=".8"/><path d="M8 29L21 16l1 3z" fill="#cdeaff" opacity=".8"/><path d="M2 24L18 11l2 2z" fill="#cdeaff" opacity=".8"/><circle cx="22" cy="10" r="6" fill="#fff6c8" stroke="#e0a818" stroke-width="1.5"/><circle cx="22" cy="10" r="3" fill="#ffe060"/>',
    // sea
    '<path d="M4 16c5-8 16-8 21 0-5 8-16 8-21 0z" fill="#f47c20" stroke="#9a4308"/><path d="M24 16l6-6v12z" fill="#f47c20" stroke="#9a4308" stroke-linejoin="round"/><circle cx="9.5" cy="14.5" r="2" fill="#fff"/><circle cx="9.5" cy="14.5" r="1" fill="#000"/><path d="M14 10c1 4 1 8 0 12M18 11c1 3 1 7 0 10" stroke="#fff" stroke-width="1.3" fill="none" opacity=".8"/>',
    '<path d="M6 16C6 8 10 4 16 4s10 4 10 12z" fill="#8e4fc2" stroke="#4a1f70"/><path d="M7 16c-1 5-4 7-5 10M12 16c0 5-2 8-1 12M17 16c0 5 2 8 1 12M22 16c1 4 3 7 6 9M26 16c2 3 3 5 4 6" stroke="#8e4fc2" stroke-width="2.6" fill="none" stroke-linecap="round"/><circle cx="12" cy="11" r="2" fill="#fff"/><circle cx="20" cy="11" r="2" fill="#fff"/><circle cx="12.4" cy="11.4" r="1" fill="#000"/><circle cx="20.4" cy="11.4" r="1" fill="#000"/>',
    '<g stroke="#9a1a10" stroke-width="1.6" fill="none"><path d="M9 20l-5 3M9 23l-4 5M23 20l5 3M23 23l4 5M12 12l-2-4M20 12l2-4"/></g><circle cx="9" cy="7" r="1.8" fill="#000"/><circle cx="23" cy="7" r="1.8" fill="#000"/><ellipse cx="16" cy="20" rx="9" ry="6.5" fill="#e0402a" stroke="#8a1a10"/><path d="M7 14c-3-1-5-4-4-7 3 0 5 3 5 5M25 14c3-1 5-4 4-7-3 0-5 3-5 5" fill="#e0402a" stroke="#8a1a10"/><path d="M12 18c2 1 6 1 8 0" stroke="#8a1a10" fill="none"/>',
    '<path d="M16 27L4 13c3-6 8-9 12-9s9 3 12 9z" fill="#f7a8b8" stroke="#a84860" stroke-linejoin="round"/><path d="M16 27L9 8M16 27l-1-23M16 27l6-22M16 27l9-17M16 27L7 11" stroke="#d06a82" stroke-width="1.1" fill="none"/><rect x="13" y="25" width="6" height="4" rx="1" fill="#e48aa0" stroke="#a84860"/>',
    '<path d="M3 18c0-6 6-10 13-10 7 0 11 4 11 9 0 2-1 4-3 5l5 4c-3 1-6 0-8-2-2 1-5 1-8 1C7 25 3 23 3 18z" fill="#3570b8" stroke="#163c70"/><path d="M5 20c4 3 12 3 18 0" fill="#bcd8f0"/><circle cx="9" cy="16" r="1.2" fill="#000"/><path d="M14 8c-1-2-1-4 0-5M14 8c-2-2-4-2-5-1M14 8c2-2 4-2 5-1" stroke="#6fc4f0" stroke-width="1.4" fill="none"/>',
    '<path d="M6 16c0-7 4-11 10-11s10 4 10 11c-3 1-17 1-20 0z" fill="#f08ac8" stroke="#a03a80" opacity=".95"/><path d="M9 17c-1 4 1 7-1 11M13 17c1 4-1 7 1 11M17 17c-1 4 1 7-1 11M21 17c1 4-1 7 1 11M24 17c0 3 2 5 1 8" stroke="#d05aa8" stroke-width="1.5" fill="none" stroke-linecap="round"/><ellipse cx="12" cy="10" rx="2" ry="1.3" fill="#fff" opacity=".6"/>',
    // music
    '<path d="M20 12L28 4l2 2-8 8z" fill="#5a3a1a"/><rect x="27" y="2" width="4" height="4" fill="#3a2410" transform="rotate(45 29 4)"/><circle cx="12" cy="21" r="8" fill="#d08a3a" stroke="#6b3a10"/><circle cx="17.5" cy="14.5" r="5.5" fill="#d08a3a" stroke="#6b3a10"/><circle cx="14" cy="18" r="2.5" fill="#3a2410"/><path d="M8 25l3 3" stroke="#3a2410" stroke-width="2"/><path d="M11 21l12-12" stroke="#f5e8c8" stroke-width=".7"/>',
    '<path d="M4 12v12c0 3 5 5 12 5s12-2 12-5V12z" fill="#d8302c" stroke="#7a1010"/><ellipse cx="16" cy="12" rx="12" ry="4.5" fill="#f5f0e0" stroke="#7a1010"/><path d="M4 16l6 12M10 17l6 11M16 17l6 11M22 17l5 10" stroke="#f5d33a" stroke-width="1.2" fill="none"/><path d="M8 3l7 9M26 3l-8 9" stroke="#8a5a2a" stroke-width="2" stroke-linecap="round"/><circle cx="8" cy="3" r="1.6" fill="#f5f0e0"/><circle cx="26" cy="3" r="1.6" fill="#f5f0e0"/>',
    '<path d="M3 17h15l8-8v16l-8-8" fill="#e8b830" stroke="#8a6a10" stroke-linejoin="round"/><rect x="3" y="15" width="16" height="4" fill="#f5d050" stroke="#8a6a10"/><rect x="8" y="11" width="2.2" height="4" fill="#c89a20"/><rect x="11.5" y="11" width="2.2" height="4" fill="#c89a20"/><rect x="15" y="11" width="2.2" height="4" fill="#c89a20"/><rect x="1.5" y="15.5" width="2" height="3" fill="#8a6a10"/><ellipse cx="26" cy="17" rx="1.6" ry="8" fill="#f8e08a" stroke="#8a6a10"/>',
    '<rect x="3" y="8" width="26" height="17" fill="#fff" stroke="#222" stroke-width="1.4"/><path d="M6.7 8v17M10.4 8v17M14.1 8v17M17.8 8v17M21.5 8v17M25.2 8v17" stroke="#555" stroke-width=".8"/><g fill="#111"><rect x="5.3" y="8" width="2.6" height="10"/><rect x="9" y="8" width="2.6" height="10"/><rect x="16.4" y="8" width="2.6" height="10"/><rect x="20.1" y="8" width="2.6" height="10"/><rect x="23.8" y="8" width="2.6" height="10"/></g><rect x="3" y="5" width="26" height="3" fill="#6a2a1a"/>',
    '<path d="M10 7l14-3v16" stroke="#111" stroke-width="2.4" fill="none"/><path d="M10 7v17" stroke="#111" stroke-width="2.4"/><path d="M10 7l14-3v4l-14 3z" fill="#111"/><ellipse cx="7" cy="24" rx="4" ry="3" fill="#111" transform="rotate(-20 7 24)"/><ellipse cx="21" cy="21" rx="4" ry="3" fill="#111" transform="rotate(-20 21 21)"/>',
    '<g stroke="#333" stroke-width=".8"><rect x="3" y="8" width="4" height="18" fill="#e8302c"/><rect x="8.5" y="9.5" width="4" height="15" fill="#f5901a"/><rect x="14" y="11" width="4" height="12" fill="#f5d020"/><rect x="19.5" y="12.5" width="4" height="9" fill="#3aa83a"/><rect x="25" y="14" width="4" height="6" fill="#2a6ad6"/></g><path d="M20 30l8-6" stroke="#8a5a2a" stroke-width="1.6"/><circle cx="28" cy="24" r="2" fill="#e8e0c8" stroke="#8a5a2a"/><g fill="#999"><circle cx="5" cy="10" r=".7"/><circle cx="5" cy="24" r=".7"/><circle cx="27" cy="15" r=".7"/><circle cx="27" cy="19" r=".7"/></g>',
    // weather
    '<g stroke="#f0a010" stroke-width="2.2" stroke-linecap="round"><path d="M16 2v4M16 26v4M2 16h4M26 16h4M6 6l3 3M23 23l3 3M26 6l-3 3M9 23l-3 3"/></g><circle cx="16" cy="16" r="7.5" fill="#ffd21a" stroke="#e08a00"/><path d="M12 13a5 5 0 0 1 4-3" stroke="#fff6b0" stroke-width="1.4" fill="none"/>',
    '<path d="M8 24a6 6 0 0 1 0-12a8 8 0 0 1 15-2a6.5 6.5 0 0 1 2 14z" fill="#fff" stroke="#6a8aa8" stroke-width="1.5"/><path d="M8 20h16" stroke="#dbe8f4" stroke-width="2"/>',
    '<path d="M8 18a5.5 5.5 0 0 1 0-11a7 7 0 0 1 13-2a6 6 0 0 1 2 13z" fill="#a8b8c8" stroke="#4a5a70" stroke-width="1.3"/><g fill="#2a8ae0"><path d="M9 21c-1 2-2 3-2 4a2 2 0 0 0 4 0c0-1-1-2-2-4z"/><path d="M17 21c-1 2-2 3-2 4a2 2 0 0 0 4 0c0-1-1-2-2-4z"/><path d="M13 25c-1 2-2 3-2 4a2 2 0 0 0 4 0c0-1-1-2-2-4z"/><path d="M22 25c-1 2-2 3-2 4a2 2 0 0 0 4 0c0-1-1-2-2-4z"/></g>',
    '<g stroke="#2a7ad0" stroke-width="2" stroke-linecap="round" fill="none"><path d="M16 3v26M4.7 9.5l22.6 13M4.7 22.5l22.6-13"/><path d="M13 5l3 3 3-3M13 27l3-3 3 3M4.5 13.5l4-1-1-4M27.5 18.5l-4 1 1 4M4.5 18.5l4 1-1 4M27.5 13.5l-4-1 1-4"/></g><circle cx="16" cy="16" r="2.4" fill="#bfe0ff" stroke="#2a7ad0"/>',
    '<path d="M18 2L7 18h7l-4 12 15-17h-8l5-11z" fill="#ffd21a" stroke="#a87a00" stroke-width="1.3" stroke-linejoin="round"/><path d="M17 5l-7 11" stroke="#fff6b0" stroke-width="1.2"/>',
    '<g fill="none" stroke-width="2.6"><path d="M3 26a13 13 0 0 1 26 0" stroke="#e8302c"/><path d="M5.6 26a10.4 10.4 0 0 1 20.8 0" stroke="#f5901a"/><path d="M8.2 26a7.8 7.8 0 0 1 15.6 0" stroke="#f5d020"/><path d="M10.8 26a5.2 5.2 0 0 1 10.4 0" stroke="#3aa83a"/><path d="M13.4 26a2.6 2.6 0 0 1 5.2 0" stroke="#2a6ad6"/></g><path d="M1 27h8M23 27h8" stroke="#bcd" stroke-width="2.4" stroke-linecap="round"/>',
    // shapes
    '<circle cx="16" cy="16" r="11" fill="#e0282e" stroke="#7a0a10" stroke-width="1.4"/><circle cx="16" cy="16" r="6" fill="none" stroke="#ff9a9a" stroke-width="1.4"/><circle cx="12" cy="11" r="2" fill="#fff" opacity=".6"/>',
    '<rect x="5" y="5" width="22" height="22" fill="#2a5ad6" stroke="#0a2070" stroke-width="1.4"/><rect x="10" y="10" width="12" height="12" fill="none" stroke="#9ab8ff" stroke-width="1.4"/><rect x="7" y="7" width="4" height="2" fill="#fff" opacity=".6"/>',
    '<path d="M16 3L29 27H3z" fill="#28a83a" stroke="#0a5a14" stroke-width="1.4" stroke-linejoin="round"/><path d="M16 11l6 11H10z" fill="none" stroke="#9af0a8" stroke-width="1.4"/>',
    '<path d="M16 2l4 9.5 10 .8-7.6 6.6 2.4 9.8L16 23.4l-8.8 5.3 2.4-9.8L2 12.3l10-.8z" fill="#f5c518" stroke="#9a7000" stroke-width="1.3" stroke-linejoin="round"/><path d="M16 8l2 5" stroke="#fff6b0" stroke-width="1.4"/>',
    '<path d="M16 28C6 20 3 15 3 10.5 3 6.5 6 4 9.5 4c3 0 5 2 6.5 4.5C17.5 6 19.5 4 22.5 4 26 4 29 6.5 29 10.5 29 15 26 20 16 28z" fill="#f0508a" stroke="#8a1040" stroke-width="1.3"/><ellipse cx="9.5" cy="10" rx="2.5" ry="1.6" fill="#fff" opacity=".6"/>',
    '<path d="M16 2l12 14-12 14L4 16z" fill="#8a3ad6" stroke="#40107a" stroke-width="1.3" stroke-linejoin="round"/><path d="M16 8l7 8-7 8-7-8z" fill="none" stroke="#d0a8ff" stroke-width="1.3"/>'
  ];
  const NAMES = ['Apple', 'Cherries', 'Banana', 'Grapes', 'Pear', 'Orange', 'Earth', 'Ringed planet', 'Red planet', 'Striped planet', 'Moon', 'Comet',
    'Fish', 'Octopus', 'Crab', 'Shell', 'Whale', 'Jellyfish', 'Guitar', 'Drum', 'Trumpet', 'Keyboard', 'Notes', 'Xylophone',
    'Sun', 'Cloud', 'Rain', 'Snowflake', 'Lightning', 'Rainbow', 'Circle', 'Square', 'Triangle', 'Star', 'Heart', 'Diamond'];

  const fmt = s => { s = Math.floor(s); return Math.floor(s / 60) + ':' + String(s % 60).padStart(2, '0'); };
  const shuffleArr = a => { for (let i = a.length - 1; i > 0; i--) { const j = Math.random() * (i + 1) | 0; [a[i], a[j]] = [a[j], a[i]]; } return a; };

  function open(W, api) {
    const defs = `<svg class="tt-defs" width="0" height="0" aria-hidden="true"><defs>${ART.map((a, i) => `<symbol id="tt-sym-${i}" viewBox="0 0 32 32">${a}</symbol>`).join('')}</defs></svg>`;
    W.body.innerHTML = `<div class="tt">${defs}
      <div class="tt-top">
        <div class="tt-tools"><button class="btn" data-a="choose">New</button><button class="btn" data-a="undo">Undo</button><button class="btn" data-a="hint">Hint</button><button class="btn" data-a="shuffle">Shuffle</button><button class="btn" data-a="pause">Pause</button></div>
        <div class="tt-stats"><span class="tt-lay">Pyramid</span><span>Tiles <b class="tt-left">0</b></span><span>Moves <b class="tt-moves">0</b></span><span>Time <b class="tt-time">0:00</b></span><span>Score <b class="tt-score">0</b></span></div>
      </div>
      <div class="tt-stage"><div class="tt-board"></div><div class="tt-ov"></div><div class="tt-toast"></div></div>
    </div>`;
    const $ = s => W.body.querySelector(s);
    const stage = $('.tt-stage'), board = $('.tt-board'), ov = $('.tt-ov'), toastEl = $('.tt-toast');
    const st = { lay: $('.tt-lay'), left: $('.tt-left'), moves: $('.tt-moves'), time: $('.tt-time'), score: $('.tt-score') };
    let opts = Object.assign({ highlight: false, sound: true }, api.load('opts', {}));
    const best = () => api.load('best', {});
    let L = null, T = [], els = [], alive = [], above = [], leftN = [], rightN = [];
    let sel = -1, undo = [], score = 0, time = 0, mode = 'choose', paused = false, shuffles = 0, lastMatch = -99, streak = 0, focusIdx = -1;
    let timer = 0, hintT = 0, toastT = 0, bw = 0, bh = 0, minX = 0, minY = 0;
    const snd = fn => { if (opts.sound) fn(); };

    /* ---------- geometry & rules ---------- */
    function buildNeighbors() {
      const n = T.length; above = []; leftN = []; rightN = [];
      for (let i = 0; i < n; i++) {
        const a = T[i], up = [], l = [], r = [];
        for (let j = 0; j < n; j++) {
          if (i === j) continue; const b = T[j];
          if (b.z === a.z + 1 && Math.abs(b.x - a.x) < 2 && Math.abs(b.y - a.y) < 2) up.push(j);
          else if (b.z === a.z && Math.abs(b.y - a.y) < 2) { if (b.x === a.x - 2) l.push(j); else if (b.x === a.x + 2) r.push(j); }
        }
        above.push(up); leftN.push(l); rightN.push(r);
      }
    }
    const isFree = (i, al) => { al = al || alive; return al[i] && !above[i].some(j => al[j]) && (!leftN[i].some(j => al[j]) || !rightN[i].some(j => al[j])); };
    // Reverse-play the given tiles: remove random free pairs until empty. The order is a guaranteed solution.
    function removalOrder(idxs) {
      for (let tries = 0; tries < 300; tries++) {
        const al = new Array(T.length).fill(false); idxs.forEach(i => { al[i] = true; });
        let left = idxs.length; const order = [];
        while (left) {
          const f = idxs.filter(i => al[i] && isFree(i, al));
          if (f.length < 2) break;
          const a = f.splice(Math.random() * f.length | 0, 1)[0], b = f[Math.random() * f.length | 0];
          al[a] = al[b] = false; left -= 2; order.push([a, b]);
        }
        if (!left) return order;
      }
      return null;
    }
    function deal(layoutId) {
      L = LAYOUTS.find(l => l.id === layoutId) || LAYOUTS[0];
      T = positions(L).map(p => Object.assign(p, { k: 0 }));
      buildNeighbors();
      const all = T.map((_, i) => i), order = removalOrder(all);
      // pairs: full sets of four where possible, one extra pair if the count needs it
      const kinds = shuffleArr([...Array(36).keys()]), pairs = [];
      const nPairs = T.length / 2;
      for (let q = 0; pairs.length < nPairs; q++) { const k = kinds[q % 36]; pairs.push(k); if (pairs.length < nPairs) pairs.push(k); }
      shuffleArr(pairs);
      order.forEach(([a, b], i) => { T[a].k = T[b].k = pairs[i]; });
      alive = T.map(() => true);
    }
    function reshuffle() {
      const idxs = T.map((_, i) => i).filter(i => alive[i]);
      const byKind = {}; idxs.forEach(i => { (byKind[T[i].k] = byKind[T[i].k] || []).push(T[i].k); });
      const pairs = []; Object.values(byKind).forEach(list => { for (let q = 0; q + 1 < list.length; q += 2) pairs.push(list[q]); });
      const order = removalOrder(idxs);
      if (!order) { const ks = shuffleArr(idxs.map(i => T[i].k)); idxs.forEach((i, q) => { T[i].k = ks[q]; }); return false; }
      shuffleArr(pairs); order.forEach(([a, b], q) => { T[a].k = T[b].k = pairs[q]; });
      return true;
    }
    function freeMatches() {
      const seen = {}, out = [];
      T.forEach((t, i) => { if (!isFree(i)) return; if (seen[t.k] !== undefined) out.push([seen[t.k], i]); else seen[t.k] = i; });
      return out;
    }

    /* ---------- rendering ---------- */
    function render() {
      board.innerHTML = ''; els = [];
      minX = Math.min(...T.map(t => t.x)); minY = Math.min(...T.map(t => t.y));
      const maxX = Math.max(...T.map(t => t.x)), maxY = Math.max(...T.map(t => t.y)), maxZ = Math.max(...T.map(t => t.z));
      bw = (maxX - minX) / 2 * TW + TW + 8 + maxZ * DZ; bh = (maxY - minY) / 2 * TH + TH + 8 + maxZ * DZ;
      T.forEach((t, i) => {
        const d = document.createElement('div');
        d.className = 'tt-tile'; d.dataset.i = i;
        d.style.left = ((t.x - minX) / 2 * TW + t.z * -DZ + maxZ * DZ) + 'px';
        d.style.top = ((t.y - minY) / 2 * TH - t.z * DZ + maxZ * DZ) + 'px';
        d.style.zIndex = t.z * 1000 + t.y * 30 + t.x + 1;
        d.innerHTML = `<i style="background:${SUITS[Math.floor(t.k / 6)]}"></i><svg viewBox="0 0 32 32"><use href="#tt-sym-${t.k}"/></svg>`;
        d.setAttribute('aria-label', NAMES[t.k]);
        board.appendChild(d); els.push(d);
      });
      board.style.width = bw + 'px'; board.style.height = bh + 'px';
      refresh(); fit();
    }
    function setFace(i) {
      const t = T[i], d = els[i];
      d.querySelector('i').style.background = SUITS[Math.floor(t.k / 6)];
      d.querySelector('use').setAttribute('href', '#tt-sym-' + t.k);
      d.setAttribute('aria-label', NAMES[t.k]);
    }
    function refresh() {
      els.forEach((d, i) => {
        d.style.display = alive[i] ? '' : 'none';
        const f = isFree(i);
        d.classList.toggle('tt-sel', i === sel);
        d.classList.toggle('tt-blk', opts.highlight && !f);
        d.classList.toggle('tt-free', opts.highlight && f);
        d.classList.toggle('tt-focus', i === focusIdx);
      });
      const left = alive.filter(Boolean).length;
      st.left.textContent = left; st.moves.textContent = mode === 'play' ? freeMatches().length : 0;
      st.score.textContent = score.toLocaleString(); st.time.textContent = fmt(time);
      st.lay.textContent = L ? L.name : '';
    }
    function fit() {
      if (!bw) return;
      const r = stage.getBoundingClientRect(), pad = 10;
      const s = Math.min((r.width - pad * 2) / bw, (r.height - pad * 2) / bh, 1.9);
      board.style.transform = `translate(${Math.round((r.width - bw * s) / 2)}px, ${Math.round((r.height - bh * s) / 2)}px) scale(${s})`;
    }
    W.onResize = () => setTimeout(fit, 0);
    const ro = window.ResizeObserver ? new ResizeObserver(() => fit()) : null;
    if (ro) ro.observe(stage);

    /* ---------- game flow ---------- */
    function saveGame() {
      if (mode !== 'play' || !L) { api.save('game', null); return; }
      api.save('game', { l: L.id, k: T.map(t => t.k), a: alive.map(Number).join(''), s: score, t: Math.floor(time), sh: shuffles, u: undo.slice(-40) });
    }
    function start(layoutId) {
      deal(layoutId);
      sel = -1; undo = []; score = 0; time = 0; shuffles = 0; streak = 0; lastMatch = -99; focusIdx = -1; paused = false;
      mode = 'play'; hideOv(); render(); runTimer(); saveGame();
      snd(() => { for (let q = 0; q < 8; q++) api.tone(600 + Math.random() * 600, 0.03, { type: 'triangle', vol: 0.04, at: q * 0.04 }); });
      toast(`${L.name}: ${T.length} tiles. Match free pairs!`);
    }
    function resume(g) {
      L = LAYOUTS.find(l => l.id === g.l); if (!L) return false;
      T = positions(L).map((p, i) => Object.assign(p, { k: g.k[i] }));
      if (T.length !== g.k.length) return false;
      buildNeighbors(); alive = [...g.a].map(c => c === '1');
      score = g.s; time = g.t; shuffles = g.sh || 0; undo = g.u || []; sel = -1; streak = 0; lastMatch = -99;
      mode = 'play'; render(); paused = false; togglePause(); return true;
    }
    function runTimer() { clearInterval(timer); timer = setInterval(() => { if (mode === 'play' && !paused) { time += 1; st.time.textContent = fmt(time); if (time % 10 === 0) saveGame(); } }, 1000); }
    function click(i) {
      if (mode !== 'play' || paused) return;
      if (!alive[i]) return;
      clearHint();
      if (!isFree(i)) {
        els[i].classList.remove('tt-shake'); void els[i].offsetWidth; els[i].classList.add('tt-shake');
        snd(() => api.tone(140, 0.08, { type: 'square', vol: 0.04 }));
        toast('That tile is stuck. A tile is free when nothing is on top of it and its left or right side is open.');
        return;
      }
      if (sel === i) { sel = -1; snd(() => api.tone(500, 0.03, { type: 'triangle', vol: 0.04 })); refresh(); return; }
      if (sel >= 0 && T[sel].k === T[i].k) { match(sel, i); return; }
      if (sel >= 0) snd(() => api.tone(220, 0.06, { type: 'triangle', vol: 0.05 }));
      else snd(() => api.tone(880, 0.04, { type: 'triangle', vol: 0.05 }));
      sel = i; refresh();
    }
    function match(a, b) {
      streak = time - lastMatch <= 5 ? Math.min(5, streak + 1) : 0; lastMatch = time;
      const pts = 10 + streak * 5; score += pts;
      alive[a] = alive[b] = false; sel = -1; undo.push([a, b, pts]);
      [a, b].forEach(i => els[i].classList.add('tt-gone'));
      const notes = [0, 2, 4, 7, 9, 12];
      snd(() => { const base = 523 * Math.pow(2, notes[streak] / 12); api.tone(base, 0.09, { type: 'triangle', vol: 0.07 }); api.tone(base * 1.5, 0.14, { type: 'triangle', vol: 0.06, at: 0.07 }); });
      if (streak >= 2) toast(`Tumble streak x${streak + 1}! +${pts}`);
      refresh();
      [a, b].forEach(i => { els[i].style.display = ''; });   // keep them visible while they fade out
      setTimeout(() => { [a, b].forEach(i => els[i].classList.remove('tt-gone')); refresh(); }, 260);
      afterMove();
    }
    function afterMove() {
      if (!alive.some(Boolean)) { setTimeout(win, 350); return; }
      if (!freeMatches().length) setTimeout(stuck, 400);
      saveGame();
    }
    function doUndo() {
      if (mode !== 'play' || paused) return;
      const u = undo.pop(); if (!u) { toast('Nothing to undo.'); return; }
      alive[u[0]] = alive[u[1]] = true; score = Math.max(0, score - u[2] - 5); sel = -1; streak = 0;
      snd(() => api.tone(440, 0.06, { type: 'triangle', vol: 0.05, to: 300 }));
      refresh(); saveGame();
    }
    function clearHint() { clearTimeout(hintT); els.forEach(d => d.classList.remove('tt-hint')); }
    function hint() {
      if (mode !== 'play' || paused) return;
      clearHint();
      const m = freeMatches();
      if (!m.length) { stuck(); return; }
      const [a, b] = m[Math.random() * m.length | 0];
      els[a].classList.add('tt-hint'); els[b].classList.add('tt-hint');
      score = Math.max(0, score - 15); refresh();
      snd(() => { api.tone(1046, 0.05, { type: 'sine', vol: 0.05 }); api.tone(1318, 0.08, { type: 'sine', vol: 0.05, at: 0.06 }); });
      toast(`Try the ${NAMES[T[a].k].toLowerCase()} pair (-15 points).`);
      hintT = setTimeout(clearHint, 2600);
    }
    function doShuffle() {
      if (mode !== 'play' || paused) return;
      clearHint();
      score = Math.max(0, score - 100); shuffles++; time += 30; sel = -1; streak = 0; undo = [];
      const ok = reshuffle();
      T.forEach((_, i) => { if (alive[i]) setFace(i); });
      els.forEach((d, i) => { if (alive[i]) { d.classList.remove('tt-mix'); void d.offsetWidth; d.classList.add('tt-mix'); } });
      snd(() => { api.noise(0.5, { ft: 'bandpass', f: 1400, q: 0.6, vol: 0.06 }); for (let q = 0; q < 10; q++) api.tone(300 + Math.random() * 900, 0.025, { type: 'square', vol: 0.025, at: q * 0.045 }); });
      hideOv(); refresh(); saveGame();
      toast(ok ? 'Shuffled! (-100 points, +30 seconds)' : 'Shuffled, but this stack is tricky. Undo is cleared.');
      if (!freeMatches().length) setTimeout(stuck, 500);
    }
    function win() {
      if (mode !== 'play') return;
      mode = 'won'; clearInterval(timer);
      const bonus = Math.max(0, 900 - time) * 2 + (shuffles ? 0 : 250);
      score += bonus;
      const b = best(), prev = b[L.id], newBest = !prev || time < prev.t;
      if (newBest) { b[L.id] = { t: time, s: score, n: api.user || 'Player' }; api.save('best', b); }
      api.save('game', null);
      snd(() => { api.sfx.tada(); [523, 659, 784, 1046, 1318].forEach((f, q) => api.tone(f, 0.18, { type: 'triangle', vol: 0.06, at: 0.5 + q * 0.09 })); });
      const got = api.earn(L.pay, `clearing the ${L.name} in Tile Tumble`);
      refresh();
      celebrate();
      showOv(`<div class="tt-h">Board cleared!</div><p>You cleared the <b>${L.name}</b>.</p>
        <table class="tt-tbl"><tr><td>Time</td><td>${fmt(time)}</td></tr><tr><td>Speed bonus</td><td>${(Math.max(0, 900 - time) * 2).toLocaleString()}</td></tr><tr><td>No-shuffle bonus</td><td>${shuffles ? 0 : 250}</td></tr><tr class="tt-tot"><td>Score</td><td>${score.toLocaleString()}</td></tr></table>
        <p class="tt-good">${newBest ? (prev ? `New best time! (was ${fmt(prev.t)})` : 'First clear: new best time!') : `Best time: ${fmt(prev.t)}`}</p>
        ${got ? `<p class="tt-money">+$${L.pay}.00 play money</p>` : ''}
        <div class="tt-btns"><button class="btn" data-a="again">Play again</button><button class="btn" data-a="choose">Choose layout</button></div>`);
    }
    function stuck() {
      if (mode !== 'play' || freeMatches().length || !alive.some(Boolean)) return;
      snd(() => { api.tone(330, 0.2, { type: 'triangle', vol: 0.06 }); api.tone(247, 0.3, { type: 'triangle', vol: 0.06, at: 0.18 }); });
      showOv(`<div class="tt-h">No more moves</div><p>There are no free matching pairs left.</p>
        <p class="tt-small">Shuffle the remaining ${alive.filter(Boolean).length} tiles (-100 points, +30 seconds), undo some moves, or give up and start over.</p>
        <div class="tt-btns"><button class="btn" data-a="shuffle">Shuffle</button><button class="btn" data-a="undoov" ${undo.length ? '' : 'disabled'}>Undo</button><button class="btn" data-a="giveup">Give up</button></div>`);
    }
    function giveUp() {
      mode = 'lost'; clearInterval(timer); api.save('game', null);
      snd(() => [392, 330, 262].forEach((f, q) => api.tone(f, 0.2, { type: 'triangle', vol: 0.06, at: q * 0.16 })));
      showOv(`<div class="tt-h">Game over</div><p>${alive.filter(Boolean).length} tiles were left on the ${L.name}. Every deal can be solved, so give it another go!</p>
        <div class="tt-btns"><button class="btn" data-a="again">Try again</button><button class="btn" data-a="choose">Choose layout</button></div>`);
    }
    function celebrate() {
      for (let q = 0; q < 30; q++) {
        const s = document.createElement('i'); s.className = 'tt-conf';
        s.style.left = Math.random() * 100 + '%'; s.style.background = SUITS[q % 6];
        s.style.animationDelay = (Math.random() * 0.8) + 's'; s.style.animationDuration = (1.6 + Math.random()) + 's';
        stage.appendChild(s); setTimeout(() => s.remove(), 3200);
      }
    }
    function choose() {
      if (mode === 'play' && alive.some(Boolean) && undo.length) saveGame();
      const was = mode; mode = mode === 'play' ? 'play' : 'choose';
      const b = best();
      showOv(`<div class="tt-logo">Tile <span>Tumble</span></div><p class="tt-small">Pick a layout. Every deal can be solved.</p>
        <div class="tt-cards">${LAYOUTS.map(l => `<button class="tt-card" data-l="${l.id}"><canvas width="96" height="64"></canvas><b>${l.name}</b><small>${'&#9733;'.repeat(l.stars)}${'&#9734;'.repeat(4 - l.stars)} &middot; ${positions(l).length} tiles</small><small>${b[l.id] ? 'Best ' + fmt(b[l.id].t) : 'Not cleared yet'}</small></button>`).join('')}</div>
        <div class="tt-btns">${was === 'play' ? '<button class="btn" data-a="close">Back to game</button>' : ''}<button class="btn" data-a="howto">How to play</button></div>`, true);
      ov.querySelectorAll('.tt-card').forEach(c => miniMap(c.querySelector('canvas'), LAYOUTS.find(l => l.id === c.dataset.l)));
      if (was === 'play' && !paused) { paused = true; }
    }
    function miniMap(cv, l) {
      const g = cv.getContext('2d'), P = positions(l);
      const maxX = Math.max(...P.map(p => p.x)) + 2, maxY = Math.max(...P.map(p => p.y)) + 2;
      const s = Math.min(88 / maxX, 56 / maxY) , ox = (96 - maxX * s) / 2, oy = (64 - maxY * s) / 2;
      P.sort((a, b) => a.z - b.z || a.y - b.y || a.x - b.x).forEach(p => {
        const sh = ['#f5ecd0', '#e8f0ff', '#d8f5e8', '#ffe8d0', '#f8d8f0'][p.z % 5];
        g.fillStyle = 'rgba(0,0,0,.35)'; g.fillRect(ox + p.x * s - p.z * 1.2 + 1, oy + p.y * s - p.z * 1.2 + 1, 2 * s - 1, 2 * s - 1);
        g.fillStyle = sh; g.fillRect(ox + p.x * s - p.z * 1.2, oy + p.y * s - p.z * 1.2, 2 * s - 1, 2 * s - 1);
      });
    }
    function showOv(html, wide) { ov.innerHTML = `<div class="tt-panel${wide ? ' tt-wide' : ''}">${html}</div>`; ov.style.display = 'flex'; }
    function hideOv() { ov.style.display = 'none'; ov.innerHTML = ''; }
    function toast(m) { toastEl.textContent = m; toastEl.classList.add('tt-on'); clearTimeout(toastT); toastT = setTimeout(() => toastEl.classList.remove('tt-on'), 2600); }
    function togglePause() {
      if (mode !== 'play') return;
      paused = !paused;
      board.classList.toggle('tt-hide', paused);
      $('[data-a=pause]').textContent = paused ? 'Resume' : 'Pause';
      if (paused) showOv(`<div class="tt-h">Paused</div><p>The clock is stopped at ${fmt(time)}.</p><div class="tt-btns"><button class="btn" data-a="resume">Resume</button></div>`);
      else hideOv();
    }
    const HOWTO = 'Clear the board by removing matching pairs of tiles.\n\n' +
      'Click or tap a tile, then click its twin. Both must be free: nothing stacked on top, and an open left or right side (a tile squeezed between neighbours on both sides is stuck).\n\n' +
      'Plan ahead! Each picture appears four times, so choose which pair to take carefully. Every deal can be solved.\n\n' +
      'Hint shows a pair (-15 points). Undo takes back a move. Shuffle mixes the tiles still on the board (-100 points and +30 seconds). Options > Highlight free tiles dims the stuck ones.\n\n' +
      'Scoring: 10 points a pair, more for quick streaks, plus a speed bonus and a no-shuffle bonus when you clear the board. Your best time for each layout is saved.\n\n' +
      'Keys: arrows move between free tiles, Space or Enter picks one, H hint, U undo, S shuffle, P pause.';
    function howTo() { if (mode === 'play' && !paused) togglePause(); api.msgBox('How to play Tile Tumble', HOWTO); }
    function showBest() {
      const b = best();
      api.msgBox('Tile Tumble best times', LAYOUTS.map(l => `${l.name}: ${b[l.id] ? fmt(b[l.id].t) + '  (' + b[l.id].s.toLocaleString() + ' pts)' : 'not cleared yet'}`).join('\n'));
    }

    /* ---------- input ---------- */
    board.addEventListener('pointerdown', e => {
      // Pick the tile under the exact point (touch adjustment can otherwise hand us a neighbour).
      const hit = document.elementFromPoint(e.clientX, e.clientY);
      const d = (hit && hit.closest && hit.closest('.tt-tile')) || e.target.closest('.tt-tile'); if (!d || !board.contains(d)) return;
      e.preventDefault(); focusIdx = -1; click(+d.dataset.i);
    });
    W.body.addEventListener('click', e => {
      const c = e.target.closest('.tt-card'); if (c) { snd(() => api.sfx.click()); start(c.dataset.l); return; }
      const b = e.target.closest('[data-a]'); if (!b || b.disabled) return;
      const a = b.dataset.a;
      if (a === 'choose') choose();
      else if (a === 'undo') doUndo();
      else if (a === 'undoov') { hideOv(); doUndo(); }
      else if (a === 'hint') hint();
      else if (a === 'shuffle') { if (mode === 'play') { if (paused && ov.querySelector('[data-a=resume]')) togglePause(); doShuffle(); } }
      else if (a === 'pause' || a === 'resume') togglePause();
      else if (a === 'again') start(L.id);
      else if (a === 'giveup') giveUp();
      else if (a === 'howto') howTo();
      else if (a === 'close') { hideOv(); paused = false; board.classList.remove('tt-hide'); }
    });
    function moveFocus(dx, dy) {
      const free = T.map((_, i) => i).filter(i => isFree(i));
      if (!free.length) return;
      if (focusIdx < 0 || !free.includes(focusIdx)) { focusIdx = free[0]; refresh(); return; }
      const c = T[focusIdx];
      let bestI = -1, bestD = 1e9;
      free.forEach(i => { if (i === focusIdx) return; const t = T[i], ddx = t.x - c.x, ddy = t.y - c.y;
        if (dx && Math.sign(ddx) !== dx) return; if (dy && Math.sign(ddy) !== dy) return;
        const d = dx ? Math.abs(ddx) + Math.abs(ddy) * 2 : Math.abs(ddy) + Math.abs(ddx) * 2; if (d < bestD) { bestD = d; bestI = i; } });
      if (bestI >= 0) { focusIdx = bestI; snd(() => api.tone(1200, 0.015, { type: 'square', vol: 0.02 })); }
      refresh();
    }
    W.onKey = e => {
      const k = e.key.toLowerCase();
      if (k === 'p') { e.preventDefault(); togglePause(); return; }
      if (mode !== 'play' || paused) return;
      if (k === 'h') { e.preventDefault(); hint(); }
      else if (k === 'u' || k === 'backspace' || (k === 'z' && (e.ctrlKey || e.metaKey))) { e.preventDefault(); doUndo(); }
      else if (k === 's') { e.preventDefault(); doShuffle(); }
      else if (k === 'arrowleft') { e.preventDefault(); moveFocus(-1, 0); }
      else if (k === 'arrowright') { e.preventDefault(); moveFocus(1, 0); }
      else if (k === 'arrowup') { e.preventDefault(); moveFocus(0, -1); }
      else if (k === 'arrowdown') { e.preventDefault(); moveFocus(0, 1); }
      else if ((k === ' ' || k === 'enter') && focusIdx >= 0) { e.preventDefault(); click(focusIdx); }
      else if (k === 'escape') { sel = -1; refresh(); }
    };

    api.menubar([
      { label: 'Game', items: () => [
        { label: 'New game (choose layout)...', fn: choose },
        { label: 'Restart this layout', fn: () => L && start(L.id), disabled: !L },
        '-',
        { label: 'Undo', fn: doUndo, disabled: mode !== 'play' || !undo.length },
        { label: 'Hint', fn: hint, disabled: mode !== 'play' },
        { label: 'Shuffle remaining tiles', fn: () => { if (paused) togglePause(); doShuffle(); }, disabled: mode !== 'play' },
        { label: paused ? 'Resume' : 'Pause', fn: togglePause, disabled: mode !== 'play' },
        '-',
        { label: 'Best times', fn: showBest },
        { label: 'How to play', fn: howTo },
        '-', { label: 'Exit', fn: () => api.close() }
      ] },
      { label: 'Options', items: () => [
        { label: (opts.highlight ? '[x] ' : '[ ] ') + 'Highlight free tiles', fn: () => { opts.highlight = !opts.highlight; api.save('opts', opts); refresh(); } },
        { label: (opts.sound ? '[x] ' : '[ ] ') + 'Sound', fn: () => { opts.sound = !opts.sound; api.save('opts', opts); } }
      ] }
    ]);
    W.onMin = () => { if (mode === 'play' && !paused) togglePause(); };
    W.onClose = () => { clearInterval(timer); clearTimeout(hintT); clearTimeout(toastT); if (ro) ro.disconnect(); if (mode === 'play') saveGame(); };

    const saved = api.load('game', null);
    if (!(saved && resume(saved))) { deal('pyramid'); mode = 'choose'; render(); choose(); }
    runTimer();
  }

  (window.RETRO_APPS = window.RETRO_APPS || []).push({
    id: 'tilematch', label: 'Tile Tumble', kind: 'store', cat: 'game', year: 2000, price: 14.95, sizeKB: 4800,
    help: 'Clear stacks of picture tiles by matching free pairs. Clearing a layout earns money.',
    publisher: 'Bluefin Pixel Works', genre: 'Puzzle solitaire',
    tagline: 'Match the pairs. Topple the stack.',
    blurb: 'A relaxing tile-matching solitaire with 144 hand-drawn tiles: fruits, planets, sea creatures, instruments, weather and shapes. Clear six stacked layouts, from the gentle Pyramid to the towering Fortress. Every deal can be solved, with hints, undo, shuffle, and best times for every layout.',
    box: { bg: '#0f4a5a', fg: '#fffbe8', accent: '#ffc83a' },
    icon: '<svg viewBox="0 0 32 32" shape-rendering="crispEdges" aria-hidden="true"><rect width="32" height="32" fill="#0f4a5a"/><rect x="5" y="9" width="12" height="16" fill="#8a7748"/><rect x="4" y="8" width="12" height="16" fill="#fffbe8" stroke="#6a5a30"/><circle cx="10" cy="16" r="4" fill="#d8262c" shape-rendering="auto"/><rect x="16" y="5" width="12" height="16" fill="#8a7748"/><rect x="15" y="4" width="12" height="16" fill="#fffbe8" stroke="#6a5a30"/><path d="M21 7l2 4 4 .5-3 2.5 1 4-4-2-4 2 1-4-3-2.5 4-.5z" fill="#f5c518" shape-rendering="auto"/><rect x="19" y="23" width="10" height="6" fill="#ffc83a"/></svg>',
    window: { w: 720, h: 580 },
    css: `.tt{display:flex;flex-direction:column;height:100%;font-family:var(--ui);background:#d4d0c8}
      .tt-defs{position:absolute;width:0;height:0;overflow:hidden}
      .tt-top{display:flex;flex-wrap:wrap;align-items:center;gap:4px 8px;padding:4px 6px;background:linear-gradient(#f2f4f8,#c9d2e0);border-bottom:1px solid #8a9ab0}
      .tt-tools{display:flex;gap:3px;flex-wrap:wrap}
      .tt-tools .btn{min-width:0;padding:3px 9px}
      .tt-stats{display:flex;gap:10px;flex-wrap:wrap;align-items:center;font-size:12px;color:#123;margin-left:auto}
      .tt-stats b{font-family:Tahoma,Verdana,sans-serif;color:#0a3a6a}
      .tt-lay{font-weight:bold;color:#0f4a5a;font-style:italic}
      .tt-stage{position:relative;flex:1;min-height:0;overflow:hidden;background:radial-gradient(ellipse at 50% 35%,#2a8a8a 0%,#15596a 45%,#0a2a3a 100%)}
      .tt-stage:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(45deg,rgba(255,255,255,.035) 0 2px,transparent 2px 14px),repeating-linear-gradient(-45deg,rgba(255,255,255,.035) 0 2px,transparent 2px 14px);pointer-events:none}
      .tt-board{position:absolute;left:0;top:0;transform-origin:0 0;transition:opacity .2s}
      .tt-board.tt-hide{opacity:0;pointer-events:none}
      .tt-tile{position:absolute;width:${TW}px;height:${TH}px;box-sizing:border-box;border-radius:4px;border:1px solid #9c8a5c;cursor:pointer;touch-action:none;
        background:linear-gradient(135deg,#fffef6 0%,#f6efd8 60%,#eadfc0 100%);
        box-shadow:1px 1px 0 #d9c99a,2px 2px 0 #cdb985,3px 3px 0 #bea66e,4px 4px 0 #ad955c,5px 5px 0 #8f7a48,6px 7px 7px rgba(0,0,0,.5);transition:filter .15s,background .15s}
      .tt-tile svg{position:absolute;left:3px;top:6px;width:${TW - 8}px;height:${TW - 8}px;pointer-events:none}
      .tt-tile i{position:absolute;left:3px;top:3px;width:5px;height:5px;border-radius:50%;opacity:.8;pointer-events:none}
      .tt-tile.tt-blk{filter:brightness(.72) saturate(.7)}
      .tt-tile.tt-free{background:linear-gradient(135deg,#ffffff 0%,#fbf6e4 60%,#f3e8c8 100%)}
      .tt-tile.tt-sel{background:linear-gradient(135deg,#fff7b0,#ffd84a);border-color:#c07a00;box-shadow:0 0 0 2px #ff9a00,1px 1px 0 #d9c99a,2px 2px 0 #c9b47e,3px 3px 0 #b39c64,4px 4px 0 #8f7a48,5px 6px 8px rgba(0,0,0,.5)}
      .tt-tile.tt-focus{outline:2px dashed #0a3a9a;outline-offset:1px}
      .tt-tile.tt-hint{animation:tt-pulse .5s ease-in-out infinite alternate}
      @keyframes tt-pulse{from{background:#fffef6}to{background:#9ef0ff;border-color:#0a8aaa}}
      .tt-tile.tt-shake{animation:tt-shake .3s}
      @keyframes tt-shake{25%{margin-left:-3px}75%{margin-left:3px}}
      .tt-tile.tt-gone{animation:tt-gone .26s forwards;pointer-events:none}
      @keyframes tt-gone{to{opacity:0;transform:translateY(-14px) scale(1.15)}}
      .tt-tile.tt-mix{animation:tt-mix .45s}
      @keyframes tt-mix{0%{transform:rotateY(0)}50%{transform:rotateY(90deg)}100%{transform:rotateY(0)}}
      .tt-ov{position:absolute;inset:0;display:none;align-items:center;justify-content:center;padding:8px;background:rgba(5,25,35,.45);z-index:2}
      .tt-panel{background:linear-gradient(#ffffff,#e4ecf4);border:1px solid #5a7a9a;border-radius:8px;box-shadow:0 6px 24px rgba(0,0,0,.5),inset 0 1px 0 #fff;padding:14px 18px;max-width:360px;width:100%;box-sizing:border-box;text-align:center;font-size:13px;max-height:100%;overflow:auto}
      .tt-panel.tt-wide{max-width:560px}
      .tt-panel p{margin:6px 0}
      .tt-h{font:bold italic 20px Verdana,Tahoma,sans-serif;color:#0f4a5a;margin-bottom:6px}
      .tt-logo{font:bold italic 28px "Trebuchet MS",Verdana,sans-serif;color:#0f4a5a;text-shadow:1px 1px 0 #fff,2px 2px 0 #9ac}
      .tt-logo span{color:#e08a00}
      .tt-small{font-size:11px;color:#345}
      .tt-good{color:#0a6a2a;font-weight:bold}
      .tt-money{color:#0a6a2a;font-weight:bold;font-size:14px}
      .tt-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px;margin:10px 0}
      .tt-card{display:flex;flex-direction:column;align-items:center;gap:2px;padding:6px;border:1px solid #8aa0b8;border-radius:6px;background:linear-gradient(#fbfdff,#dce6f0);cursor:pointer;font:12px var(--ui);color:#123}
      .tt-card:hover,.tt-card:focus{border-color:#e08a00;background:linear-gradient(#fffbe8,#ffe8b0)}
      .tt-card canvas{width:96px;height:64px;background:#15596a;border-radius:3px}
      .tt-card b{font-size:13px;color:#0f4a5a}
      .tt-card small{font-size:11px;color:#456}
      .tt-btns{display:flex;gap:6px;justify-content:center;flex-wrap:wrap;margin-top:8px}
      .tt-btns .btn{min-width:96px;padding:4px 10px}
      .tt-tbl{margin:6px auto;border-collapse:collapse;font-size:12px}
      .tt-tbl td{padding:2px 10px;text-align:left}.tt-tbl td:last-child{text-align:right}
      .tt-tot td{border-top:1px solid #8aa;font-weight:bold}
      .tt-toast{position:absolute;left:50%;bottom:10px;transform:translateX(-50%);max-width:90%;background:rgba(255,255,240,.95);border:1px solid #8a7a4a;border-radius:12px;padding:4px 12px;font-size:12px;color:#222;opacity:0;transition:opacity .3s;pointer-events:none;z-index:3;text-align:center}
      .tt-toast.tt-on{opacity:1}
      .tt-conf{position:absolute;top:-10px;width:7px;height:10px;z-index:1;animation:tt-fall 2s linear forwards;pointer-events:none}
      @keyframes tt-fall{to{transform:translateY(700px) rotate(540deg)}}
      @media (max-width:500px){.tt-stats{margin-left:0;gap:8px}.tt-tools .btn{padding:3px 7px}}`,
    open
  });
})();
